### ISSUE TITLE
Feature request: Init logic

### ISSUE THREAD

**Issue by yaymalaga** [MaikuB/flutter_app_templates#7]
Hello there!

I was playing with Provider and Change Notification, and then I discovered Mobx, which I'm looking forward to implement in my future projects.

One of the biggest challenges I have faced with provider is related to the initstate. I haven't found yet any really good method to run async code when a view is selected for the first time. As using provider you can't access the context in the initstate, the only thing I can think of is using a Consumer widget as a parent and pass the store as a parameter of the view. 

My goal was that every page of the bottomnavbar could trigger its own init logic. Currently, I'm calling the methods once a bottombaritem is pressed, but then the logic for the first view, which is automatically selected, is not handled. 

I think this could be a good real world example, so I was wondering if you could improve this layout to cover this scenario.

**Comment by MaikuB** [comment]
I agree that the scenario you described is more realistic. However, I won't be including in these templates as they are suppose to match more around what you'd get if you created a brand new Android project with the same navigation pattern. You may find this example app that I've written [here](https://github.com/MaikuB/supnews) to be useful
